### ISSUE TITLE
Error executing script. Unexpected error for call_service at pos 1: 'poe-out'

### ISSUE THREAD

**Issue by robiecz** [tomaae/homeassistant-mikrotik_router#100]
Hello,
I get an error, when I turn off/on an interface even the interface turn off/on.
Log:
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 254, in _async_step
    await getattr(
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 464, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1455, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1490, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 595, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 664, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 632, in _handle_entity_call
    await result
  File "/config/custom_components/mikrotik_router/switch.py", line 324, in async_turn_on
    if self._data["poe-out"] == "off":
KeyError: 'poe-out'

Many thx!
Tomas

**Comment by tomaae** [comment]
Hi,
Can you give me information about your setup?
 - Home Assistant version: 
 - Mikrotik Router integration version: 
 - Mikrotik Hardware: 
 - RouterOS version: 

Also, which interface is throwing this? All of them?

**Comment by robiecz** [comment]
Sure:
## System Health

version | core-2021.2.3
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
virtualenv | false
python_version | 3.8.7
os_name | Linux
os_version | 5.4.83-v7l
arch | armv7l
timezone | Europe/Prague

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 4853
Installed Version | 1.11.3
Stage | running
Available Repositories | 750
Installed Repositories | 10

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Hass.io</summary>

host_os | Home Assistant OS 5.12
-- | --
update_channel | stable
supervisor_version | supervisor-2021.02.11
docker_version | 19.03.13
disk_total | 28.6 GB
disk_used | 8.7 GB
healthy | true
supported | true
board | rpi4
supervisor_api | ok
version_api | ok
installed_addons | File editor (5.2.0), SSH & Web Terminal (8.0.3), deCONZ (6.7.2), Check Home Assistant configuration (3.6.0)

</details>

<details><summary>Lovelace</summary>

dashboards | 1
-- | --
resources | 3
views | 1
mode | storage

</details>

Mikrotik:
RBD52G-5HacD2HnD
FW: 6.48.1

It seems, that the issue is just with non physical ports. The problematic interface is Type: L2TP Client.

**Comment by tomaae** [comment]
Can you give me output of "/interface print terse" and "/interface ethernet print terse". You can mask your mac addresses if you want.

**Comment by robiecz** [comment]
<img width="631" alt="mikrotik-2" src="https://user-images.githubusercontent.com/25706105/109487009-eff44680-7a83-11eb-937f-a0a6fd502e38.png">
<img width="593" alt="mikrotik-1" src="https://user-images.githubusercontent.com/25706105/109487013-f1257380-7a83-11eb-93e3-ae64ed972b88.png">

**Comment by tomaae** [comment]
Can you test it with master?

**Comment by robiecz** [comment]
> Can you test it with master?

What do you mean?

**Comment by robiecz** [comment]
Ok, I installed the master version.

Turning On works well, Turning Off causes the error:
[2921213184] 'poe-out'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 136, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1455, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1490, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 595, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 664, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 632, in _handle_entity_call
    await result
  File "/config/custom_components/mikrotik_router/switch.py", line 344, in async_turn_off
    if self._data["poe-out"] == "auto-on":
KeyError: 'poe-out'

**Comment by tomaae** [comment]
woops, should be ok now.

**Comment by robiecz** [comment]
> woops, should be ok now.

Great, no issues at all!
Thx man ;-).

**Comment by tomaae** [comment]
great :)
