### ISSUE TITLE
CRS309-1G-8S+ shows no interfaces[Bug]

### ISSUE THREAD

**Issue by farsonic** [tomaae/homeassistant-mikrotik_router#101]
## Describe the issue

I have configured the integration with a CRS309-1G-8S+ and the only entity is returned is "Lab-Switch Firmware update"
I have another mikrotik switch that works with this integration. 

## Expected behaviour
Expected I would see interfaces and environmental details. 

## Software versions
 - Home Assistant version: 2021.3.4
 - Mikrotik Router integration version: Current release version
 - Mikrotik Hardware:  CRS309-1G-8S+
 - RouterOS version: e.g. v6.47.7

## Traceback/Error logs

This is repeated in logs. 
2021-03-21 12:57:44 ERROR (SyncWorker_14) [custom_components.mikrotik_router.mikrotikapi] Mikrotik 192.168.0.2 error while building list for path : unknown
2021-03-21 12:57:54 ERROR (SyncWorker_0) [custom_components.mikrotik_router.mikrotikapi] Mikrotik 192.168.0.2 error while building list for path : unknown
2021-03-21 12:57:54 ERROR (SyncWorker_9) [custom_components.mikrotik_router.mikrotikapi] Mikrotik 192.168.0.2 error while building list for path : unknown
2021-03-21 12:57:54 WARNING (SyncWorker_9) [custom_components.mikrotik_router.mikrotikapi] Mikrotik Reconnected to 192.168.0.2

**Comment by tomaae** [comment]
You will need to give more information, including versions and logs.

**Comment by farsonic** [comment]
Sorry, I thought I had when I submitted it but looks liked it didn't go
through properly!

updating now

**Comment by tomaae** [comment]
I have checked the device and thats a switch, not a router. I have no experience with those, so we will need to run it in debug mode.
Just run it in debug for few minutes and we will see whats detected.
Also, are you using RouterOS or SwOS on it?

**Comment by farsonic** [comment]
It is running RouterOS and is a CRS...which is a router right?

**Comment by farsonic** [comment]
Both my Mikrotiks are routers running RouterOS....

[image: Screen Shot 2021-03-21 at 3.50.06 pm.png]

**Comment by tomaae** [comment]
This switch runs both depending on boot mode, thats why I'm asking. It most likely can act as a router as most managed switches can, but that should not really matter for integration.

Not sure what that image is, it wont show images when they are sent via email.
In any case, I will need debug logs to see what is happening.

**Comment by farsonic** [comment]
Can you advise debug commands please? Assume on MikroTik side?

**Comment by tomaae** [comment]
Here you go:
https://github.com/tomaae/homeassistant-mikrotik_router#enabling-debug

**Comment by farsonic** [comment]
This has now appeared in the logs with this enabled

2021-03-23 09:20:34 ERROR (SyncWorker_10)
[custom_components.mikrotik_router.mikrotikapi] Mikrotik 192.168.0.2 error
while building list for path : unknown
2021-03-23 09:20:34 WARNING (SyncWorker_10)
[custom_components.mikrotik_router.mikrotikapi] Mikrotik Reconnected to
192.168.0.2
2021-03-23 09:20:44 ERROR (SyncWorker_10)
[custom_components.mikrotik_router.mikrotikapi] Mikrotik 192.168.0.2 error
while building list for path : unknown
2021-03-23 09:20:44 ERROR (MainThread) [homeassistant.util.logging]
Exception in update_controller when dispatching
'mikrotik_router-update-Lab-Switch': ()
Traceback (most recent call last):
  File "/config/custom_components/mikrotik_router/sensor.py", line 210, in
update_controller
    update_items(
  File "/config/custom_components/mikrotik_router/sensor.py", line 274, in
update_items
    mikrotik_controller.data[SENSOR_TYPES[sensor][ATTR_PATH]][
KeyError: 'temperature'

**Comment by tomaae** [comment]
I need a full log for this integration since HA start. Here I can see that some queries are failing, but not which one and where it starts.

**Comment by farsonic** [comment]
ok, will look to capture this today.

**Comment by dmitritrofimenko** [comment]
I have the same issue with router 

2021-03-26 00:44:10 WARNING (SyncWorker_2) [custom_components.mikrotik_router.mikrotikapi] Mikrotik Reconnected to 192.168.88.1
2021-03-26 00:44:10 WARNING (SyncWorker_5) [custom_components.mikrotik_router.mikrotikapi] Mikrotik Reconnected to 192.168.88.1
2021-03-26 00:44:10 WARNING (SyncWorker_4) [custom_components.mikrotik_router.mikrotikapi] Mikrotik Reconnected to 192.168.88.1
2021-03-26 00:44:10 ERROR (SyncWorker_2) [custom_components.mikrotik_router.mikrotikapi] Mikrotik 192.168.88.1 error while building list for path : unknown
2021-03-26 00:44:10 ERROR (SyncWorker_5) [custom_components.mikrotik_router.mikrotikapi] Mikrotik 192.168.88.1 error while building list for path : unknown
2021-03-26 00:44:10 ERROR (SyncWorker_4) [custom_components.mikrotik_router.mikrotikapi] Mikrotik 192.168.88.1 error while building list for path : unknown


and it is probably the same as [issue 96](https://github.com/tomaae/homeassistant-mikrotik_router/issues/96)

`2021-03-26 00:50:40 ERROR (MainThread) [homeassistant.util.logging] Exception in update_controller when dispatching 'mikrotik_router-update-Mikrotik-ha2': ()
Traceback (most recent call last):
  File "/config/custom_components/mikrotik_router/binary_sensor.py", line 107, in update_controller
    update_items(
  File "/config/custom_components/mikrotik_router/binary_sensor.py", line 182, in update_items
    sensors[item_id].async_schedule_update_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 440, in async_schedule_update_ha_state
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 291, in async_write_ha_state
    raise NoEntitySpecifiedError(
homeassistant.exceptions.NoEntitySpecifiedError: No entity id specified for entity Mikrotik-ha2 Firmware update`

**Comment by dmitritrofimenko** [comment]
**solved in this way:**

on router side: system -> packages -> check for updates  (update found) -> download update and reboot  router
later just to be sure on HA side: restart HA   / empty browser cash and hard reload.

**Comment by tomaae** [comment]
> **solved in this way:**
> 
> on router side: system -> packages -> check for updates (update found) -> download update and reboot router
> later just to be sure on HA side: restart HA / empty browser cash and hard reload.

Thats some weird error. So the same device works for you?
