### ISSUE TITLE
[Bug] KeyError: 'interface'

### ISSUE THREAD

**Issue by tjorim** [tomaae/homeassistant-mikrotik_router#11]
**Describe the bug**
Following error appears in the log, everything seems to work fine.

**Expected behavior**
No errors in the log.

**Log details**
```
Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/mikrotik_router/mikrotik_controller.py", line 57, in force_update
    await self.async_update()
  File "/config/custom_components/mikrotik_router/mikrotik_controller.py", line 135, in async_update
    await self.hass.async_add_executor_job(self.get_interface_client)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/mikrotik_router/mikrotik_controller.py", line 239, in get_interface_client
    mac2ip, bridge_used = self.update_arp(mac2ip, bridge_used)
  File "/config/custom_components/mikrotik_router/mikrotik_controller.py", line 267, in update_arp
    if entry['interface'] == "bridge":
KeyError: 'interface'
```

**Software (please complete the following information):**
 - Hass.io / Home Assistant version: Hassio v195/ HA v0.105.0b6
 - HA Mikrotik Router integration version: v1.2
 - Mikrotik Hardware: hAP ac²
 - Mikrotik Software version: v6.45.8 (recently updated)

**Comment by tomaae** [comment]
Missing interfaces? was this one time occurrence?

**Comment by tjorim** [comment]
I have not seen this again. Probably just a fluke. Didn't check all interfaces.

**Comment by tomaae** [comment]
Okey. Client detection part still needs to be rewritten, so I keep this open as a reminder.
