### ISSUE TITLE
Error setting up integration

### ISSUE THREAD

**Issue by jacauc** [tomaae/homeassistant-mikrotik_router#114]
## Describe the issue
Set up new integration in latest version of HA and HACS

## How to reproduce the issue
Install integration in HACS
Install and configure Integration

## Expected behavior
Entities created and addon working.

## Screenshots
![image](https://user-images.githubusercontent.com/18201320/116590146-b58d1580-a91d-11eb-91b1-cb2172be70cc.png)
![image](https://user-images.githubusercontent.com/18201320/116590332-e9683b00-a91d-11eb-9144-e7da68a0db71.png)

## Software versions

 - Home Assistant version: core-2021.4
 - Mikrotik Router integration version: 1.7.1
 - Mikrotik Hardware: RB4011iGS
 - RouterOS version: 6.48.2

**Comment by tomaae** [comment]
can you check ha log?

**Comment by jacauc** [comment]
Yes, I've attached a screenshot of the ha logs in OP

**Comment by tomaae** [comment]
thats not a log, just a summary.
Also, please paste the log, do not take screenshot.

**Comment by LouiS22** [comment]
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 269, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/mikrotik_router/__init__.py", line 69, in async_setup_entry
    device_registry.async_get_or_create(
  File "/usr/src/homeassistant/homeassistant/helpers/device_registry.py", line 266, in async_get_or_create
    raise RequiredParameterMissing(["identifiers", "connections"])
homeassistant.exceptions.RequiredParameterMissing: (RequiredParameterMissing(...), 'Call must include at least one of the following parameters: identifiers, connections')

**Comment by tomaae** [comment]
Ah yes, but that means you are using RC 2021.5, not 2021.4
I'm already aware of this issue.

**Comment by jacauc** [comment]
Running off master but still unable to set up integration.

`2021-05-04 18:04:05 WARNING (MainThread) [homeassistant.loader] You are using a custom integration mikrotik_router which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-05-04 18:04:05 WARNING (MainThread) [homeassistant.loader] You are using a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-05-04 18:04:05 WARNING (MainThread) [homeassistant.loader] You are using a custom integration nodered which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-05-04 18:04:05 WARNING (MainThread) [homeassistant.loader] You are using a custom integration mbapi2020 which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-05-04 18:04:07 WARNING (Recorder) [homeassistant.components.recorder.util] Ended unfinished session (id=13 from 2021-05-04 15:27:35)
2021-05-04 18:04:11 WARNING (MainThread) [homeassistant.loader] You are using a custom integration dwains_dashboard which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-05-04 18:04:16 ERROR (SyncWorker_2) [custom_components.mikrotik_router.mikrotikapi] Mikrotik 192.168.xxx.xxx error while building list for path : unknown
2021-05-04 18:04:16 WARNING (SyncWorker_8) [custom_components.mikrotik_router.mikrotikapi] Mikrotik Reconnected to 192.168.xxx.xxx
2021-05-04 18:04:16 ERROR (SyncWorker_8) [custom_components.mikrotik_router.mikrotikapi] Mikrotik 192.168.xxx.xxx error while building list for path : unknown
2021-05-04 18:04:16 ERROR (MainThread) [homeassistant.components.binary_sensor] rpi_power: Error on device update!
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 407, in _async_add_entity
await entity.async_device_update(warning=False)
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 516, in async_device_update
await task
File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
result = self.fn(*self.args, **self.kwargs)
File "/usr/src/homeassistant/homeassistant/components/rpi_power/binary_sensor.py", line 42, in update
self._is_on = self._under_voltage.get()
AttributeError: 'NoneType' object has no attribute 'get'
2021-05-04 18:04:16 WARNING (SyncWorker_8) [custom_components.mikrotik_router.mikrotikapi] Mikrotik Reconnected to 192.168.xxx.xxx
2021-05-04 18:04:16 ERROR (SyncWorker_8) [custom_components.mikrotik_router.mikrotikapi] Mikrotik 192.168.xxx.xxx error while building list for path : unknown
2021-05-04 18:04:16 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Mikrotik for mikrotik_router
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 269, in async_setup
result = await component.async_setup_entry(hass, self) # type: ignore
File "/config/custom_components/mikrotik_router/__init__.py", line 71, in async_setup_entry
connections={(DOMAIN, controller.data["routerboard"]["serial-number"])},
KeyError: 'serial-number'
2021-05-04 18:04:17 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up mikrotik_router platform for sensor
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 231, in _async_setup_platform
await asyncio.shield(task)
File "/config/custom_components/mikrotik_router/sensor.py", line 224, in async_setup_entry
update_controller()
File "/config/custom_components/mikrotik_router/sensor.py", line 214, in update_controller
update_items(
File "/config/custom_components/mikrotik_router/sensor.py", line 278, in update_items
mikrotik_controller.data[SENSOR_TYPES[sensor][ATTR_PATH]][
KeyError: 'temperature'
2021-05-04 18:04:18 ERROR (MainThread) [homeassistant.components.binary_sensor] Error adding entities for domain binary_sensor with platform mikrotik_router
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 364, in async_add_entities
await asyncio.gather(*tasks)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 432, in _async_add_entity
device_info = entity.device_info
File "/config/custom_components/mikrotik_router/binary_sensor.py", line 267, in device_info
"manufacturer": self._ctrl.data["resource"]["platform"],
KeyError: 'platform'
2021-05-04 18:04:18 ERROR (MainThread) [homeassistant.components.binary_sensor] Error while setting up mikrotik_router platform for binary_sensor
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 239, in _async_setup_platform
await asyncio.gather(*pending)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 364, in async_add_entities
await asyncio.gather(*tasks)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 432, in _async_add_entity
device_info = entity.device_info
File "/config/custom_components/mikrotik_router/binary_sensor.py", line 267, in device_info
"manufacturer": self._ctrl.data["resource"]["platform"],
KeyError: 'platform'`

**Comment by tomaae** [comment]
that will be different issue. Can you debug it?
