### ISSUE TITLE
[Bug] Handle numeric interfaces names in interface_list 

### ISSUE THREAD

**Issue by ricardogfp** [tomaae/homeassistant-mikrotik_router#151]
When initializing the integration I get the following error in Home assistant logs:
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 304, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/mikrotik_router/__init__.py", line 40, in async_setup_entry
    await controller.async_update()
  File "/config/custom_components/mikrotik_router/mikrotik_controller.py", line 563, in async_update
    await self.hass.async_add_executor_job(self.get_interface_traffic)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/mikrotik_router/mikrotik_controller.py", line 722, in get_interface_traffic
    interface_list += self.data["interface"][uid]["name"] + ","
TypeError: unsupported operand type(s) for +: 'int' and 'str'

My interfaces in mikrotik doesn't have any special characters or anything:
![image](https://user-images.githubusercontent.com/50072612/145480711-74c39987-6ec5-439e-af18-3eb31b9bca64.png)

What could be the problem?

**Comment by ricardogfp** [comment]
That was it, changed "20" to "WAN20" and it worked. Thanks

**Comment by tomaae** [comment]
great. leave this issue open please, so I remember to take a look if this can be workarounded in code.
