### ISSUE TITLE
RuntimeError: Attribute hass is None

### ISSUE THREAD

**Issue by marianobntz** [tomaae/homeassistant-mikrotik_router#18]
**Describe the bug**
I just got this log in HA. Do not know if it is an error or not...

Log Details (ERROR)
Logger: homeassistant.util.logging
Source: util/logging.py:176
First occurred: 4:58:50 PM (30 occurrences)
Last logged: 5:13:36 PM

Exception in update_controller when dispatching 'mikrotik_router-update-Mikrotik': () Traceback (most recent call last): File "/config/custom_components/mikrotik_router/switch.py", line 77, in update_controller update_items(inst, mikrotik_controller, async_add_entities, switches) File "/config/custom_components/mikrotik_router/switch.py", line 109, in update_items switches[item_id].async_schedule_update_ha_state() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 447, in async_schedule_update_ha_state self.async_write_ha_state() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 290, in async_write_ha_state raise RuntimeError(f"Attribute hass is None for {self}") RuntimeError: Attribute hass is None for <Entity Mikrotik port ether1: on>
Connection lost. Reconnecting…

**Software (please complete the following information):**
 - Home Assistant version: 0.107.6 (also happened in 0.106.x)
 - HA Mikrotik Router integration version:  v1.3.1
 - Mikrotik Hardware: RB951G-2HnD
 - Mikrotik Software version: RouterOS v6.47beta35

**Additional context**

**Comment by tomaae** [comment]
I'm getting log of weird None errors from various integrations since last HA update. But lets have a look to confirm.

Do you get it every time when you restart HA?
I will need more information about whats going on when adding that switch. You will need to enable debug.
If you dont have logger already defined, add following to your configuration and restart.
```
logger:
    default: info
    logs:
        custom_components.mikrotik_router: debug
```
Once that error occurs, copy home-assistant.log, remove logger and restart HA again to stop debugging.

**Comment by marianobntz** [comment]
here are the logs with debug, is this enough?
Thanks
[home-assistant.log](https://github.com/tomaae/homeassistant-mikrotik_router/files/4383596/home-assistant.log)

**Comment by tomaae** [comment]
I have deleted the comment since it contained some email addresses, just to be safe.

There is similar error but on update, not creation this time.
On first glance, it seems like all information is okey. I will need to have a deeper look into this, maybe add additional debug information.

**Comment by marianobntz** [comment]
Ok let me know if you need anything else, like updates

**Comment by tomaae** [comment]
Home Assistant 0.107.7 was just released and I dont see any "None" errors from other integrations now.
Can you try to update HA?

**Comment by marianobntz** [comment]
just updated and still some errors show up... 

`020-03-26 11:06:05 INFO (SyncWorker_5) [root] Sending handshake.
2020-03-26 11:06:14 ERROR (MainThread) [homeassistant.util.logging] Exception in update_controller when dispatching 'mikrotik_router-update-Mikrotik': ()
Traceback (most recent call last):
  File "/config/custom_components/mikrotik_router/switch.py", line 77, in update_controller
    update_items(inst, mikrotik_controller, async_add_entities, switches)
  File "/config/custom_components/mikrotik_router/switch.py", line 109, in update_items
    switches[item_id].async_schedule_update_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 447, in async_schedule_update_ha_state
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 290, in async_write_ha_state
    raise RuntimeError(f"Attribute hass is None for {self}")
RuntimeError: Attribute hass is None for <Entity Mikrotik port ether1: on>

2020-03-26 11:06:16 INFO (MainThread) [custom_components.hpprinter.home_assistant] Updating 2020-03-26 14:06:16.002458+00:00
2020-03-26 11:06:16 INFO (SyncWorker_5) [root] Sending handshake.
2020-03-26 11:06:27 INFO (MainThread) [custom_components.hpprinter.home_assistant] Updating 2020-03-26 14:06:27.002205+00:00
2020-03-26 11:06:27 INFO (SyncWorker_2) [root] Sending handshake.
2020-03-26 11:06:38 INFO (MainThread) [custom_components.hpprinter.home_assistant] Updating 2020-03-26 14:06:38.001965+00:00
2020-03-26 11:06:38 INFO (SyncWorker_6) [root] Sending handshake.
2020-03-26 11:06:43 ERROR (MainThread) [homeassistant.components.google_assistant.http] Request for https://homegraph.googleapis.com/v1/devices:reportStateAndNotification failed: 400
2020-03-26 11:06:46 ERROR (MainThread) [homeassistant.util.logging] Exception in update_controller when dispatching 'mikrotik_router-update-Mikrotik': ()
Traceback (most recent call last):
  File "/config/custom_components/mikrotik_router/switch.py", line 77, in update_controller
    update_items(inst, mikrotik_controller, async_add_entities, switches)
  File "/config/custom_components/mikrotik_router/switch.py", line 109, in update_items
    switches[item_id].async_schedule_update_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 447, in async_schedule_update_ha_state
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 290, in async_write_ha_state
    raise RuntimeError(f"Attribute hass is None for {self}")
RuntimeError: Attribute hass is None for <Entity Mikrotik port ether1: on>

2020-03-26 11:06:49 INFO (MainThread) [custom_components.hpprinter.home_assistant] Updating 2020-03-26 14:06:49.001821+00:00
2020-03-26 11:06:49 INFO (SyncWorker_0) [root] Sending handshake.
2020-03-26 11:07:00 INFO (MainThread) [custom_components.hpprinter.home_assistant] Updating 2020-03-26 14:07:00.002459+00:00
2020-03-26 11:07:00 INFO (SyncWorker_4) [root] Sending handshake.
2020-03-26 11:07:11 INFO (MainThread) [custom_components.hpprinter.home_assistant] Updating 2020-03-26 14:07:11.001882+00:00
2020-03-26 11:07:11 INFO (SyncWorker_6) [root] Sending handshake.
2020-03-26 11:07:16 ERROR (MainThread) [homeassistant.util.logging] Exception in update_controller when dispatching 'mikrotik_router-update-Mikrotik': ()
Traceback (most recent call last):
  File "/config/custom_components/mikrotik_router/switch.py", line 77, in update_controller
    update_items(inst, mikrotik_controller, async_add_entities, switches)
  File "/config/custom_components/mikrotik_router/switch.py", line 109, in update_items
    switches[item_id].async_schedule_update_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 447, in async_schedule_update_ha_state
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 290, in async_write_ha_state
    raise RuntimeError(f"Attribute hass is None for {self}")
RuntimeError: Attribute hass is None for <Entity Mikrotik port ether1: on>

2020-03-26 11:07:22 INFO (MainThread) [custom_components.hpprinter.home_assistant] Updating 2020-03-26 14:07:22.002554+00:00
2020-03-26 11:07:22 INFO (SyncWorker_8) [root] Sending handshake.
2020-03-26 11:07:33 INFO (MainThread) [custom_components.hpprinter.home_assistant] Updating 2020-03-26 14:07:33.001888+00:00
2020-03-26 11:07:33 INFO (SyncWorker_0) [root] Sending handshake.
2020-03-26 11:07:44 INFO (MainThread) [custom_components.hpprinter.home_assistant] Updating 2020-03-26 14:07:44.002017+00:00
2020-03-26 11:07:44 INFO (SyncWorker_5) [root] Sending handshake.
2020-03-26 11:07:48 ERROR (MainThread) [homeassistant.util.logging] Exception in update_controller when dispatching 'mikrotik_router-update-Mikrotik': ()
Traceback (most recent call last):
  File "/config/custom_components/mikrotik_router/switch.py", line 77, in update_controller
    update_items(inst, mikrotik_controller, async_add_entities, switches)
  File "/config/custom_components/mikrotik_router/switch.py", line 109, in update_items
    switches[item_id].async_schedule_update_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 447, in async_schedule_update_ha_state
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 290, in async_write_ha_state
    raise RuntimeError(f"Attribute hass is None for {self}")
RuntimeError: Attribute hass is None for <Entity Mikrotik port ether1: on>

2020-03-26 11:07:55 INFO (MainThread) [custom_components.hpprinter.home_assistant] Updating 2020-03-26 14:07:55.002744+00:00
2020-03-26 11:07:55 INFO (SyncWorker_7) [root] Sending handshake.
2020-03-26 11:08:06 INFO (MainThread) [custom_components.hpprinter.home_assistant] Updating 2020-03-26 14:08:06.002759+00:00
2020-03-26 11:08:06 INFO (SyncWorker_6) [root] Sending handshake.`

**Comment by marianobntz** [comment]
Another log that might help...

> Log Details (ERROR)
Logger: homeassistant.components.switch
Source: helpers/entity.py:290
Integration: Switch (documentation, issues)
First occurred: 11:04:49 AM (1 occurrences)
Last logged: 11:04:49 AM

Error while setting up mikrotik_router platform for switch
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 179, in _async_setup_platform
    await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
  File "/config/custom_components/mikrotik_router/switch.py", line 85, in async_setup_entry
    update_controller()
  File "/config/custom_components/mikrotik_router/switch.py", line 77, in update_controller
    update_items(inst, mikrotik_controller, async_add_entities, switches)
  File "/config/custom_components/mikrotik_router/switch.py", line 109, in update_items
    switches[item_id].async_schedule_update_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 447, in async_schedule_update_ha_state
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 290, in async_write_ha_state
    raise RuntimeError(f"Attribute hass is None for {self}")
RuntimeError: Attribute hass is None for <Entity Mikrotik NAT tcp:443: on>
Connection lost. Reconnecting…

**Comment by tomaae** [comment]
ok, thanks for checking.

**Comment by tomaae** [comment]
could you run debug again using v1.4? I have added debug for entities so we can pinpoint which entity is causing the issue

**Comment by marianobntz** [comment]
[debug.log](https://github.com/tomaae/homeassistant-mikrotik_router/files/4432471/debug.log)
is this log enough? need more?

**Comment by marianobntz** [comment]
Home Assistant 0.107.7
with 
Mikrotik Router
Mikrotik router integration for Home Assistant
Authors:
tomaae
GitHub stars: 9
Last updated: 3 hours ago
Installed: v1.4

**Comment by tomaae** [comment]
yes, it is enough. I can see the issue now. 
you have 2 identical nat rules tcp:443, only difference is in-interface. they seem to do the same thing, unless I'm missing something. is there a reason for it?

**Comment by marianobntz** [comment]
yes, there is a reason for the 2 rules: the 443 inbound from the wan interface is to redirect the traffic from the mikotik router to the synology nas with home assistant. The other 443 rule is when I access my hostname from inside the lan to redirect again. I tried many other configuration options and it is the only one that works. I want to use the same hostname from outside and insider the house. (WAN or LAN)

**Comment by tomaae** [comment]
Ah, I see. The way I handle this in my network is to create DNS alias for router on both internet and inside of my network. Not sure if the same is viable for you.

Could you remove one of them just to check if integration will work fine? Just to eliminate any other potential issue.

Problem with NAT rules is that routeros does not have persistent unique ID per rule.
I'm looking into a way to make them more unique in a way that would make sense or disable any duplicate rules #20

**Comment by marianobntz** [comment]
I disabled one of the tcp:443 rules and I still have the same error: 

2020-04-05 16:47:34 DEBUG (MainThread) [custom_components.mikrotik_router.switch] Updating switch Mikrotik-interface-ether1-gateway
2020-04-05 16:47:34 ERROR (MainThread) [homeassistant.util.logging] Exception in update_controller when dispatching 'mikrotik_router-update-Mikrotik': ()
Traceback (most recent call last):
  File "/config/custom_components/mikrotik_router/switch.py", line 87, in update_controller
    update_items(inst, mikrotik_controller, async_add_entities, switches)
  File "/config/custom_components/mikrotik_router/switch.py", line 121, in update_items
    switches[item_id].async_schedule_update_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 447, in async_schedule_update_ha_state
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 290, in async_write_ha_state
    raise RuntimeError(f"Attribute hass is None for {self}")
RuntimeError: Attribute hass is None for <Entity Mikrotik port ether1: on>

**Comment by marianobntz** [comment]
I do not see this switch in my list "Mikrotik-interface-ether1-gateway", where is it defined?

**Comment by tomaae** [comment]
you need to delete it, not disable it. disabled nat rules are still shown in HA as disabled.

ether1 is probably not in HA because it crashes.

**Comment by tomaae** [comment]
v1.4.1 should fix the issue for you.

**Comment by marianobntz** [comment]
yes indeed!!! Now all I see is (correctly)

Logger: custom_components.mikrotik_router.mikrotik_controller
Source: custom_components/mikrotik_router/mikrotik_controller.py:482
First occurred: 8:22:33 PM (1 occurrences)
Last logged: 8:22:33 PM

Mikrotik 10.1.0.1 duplicate NAT rule tcp:443, entity will be unavailable.

**Comment by marianobntz** [comment]
Thank you very much for your assistance!!! Kudos!!

**Comment by tomaae** [comment]
perfect, I'm glad it works :)
