### ISSUE TITLE
[Bug] Error handling request

### ISSUE THREAD

**Issue by tjorim** [tomaae/homeassistant-mikrotik_router#2]
**Describe the bug**
I can't add the mikrotik router integration.

**To Reproduce**
1. Go to 'Configuration'
2. Click on 'Integrations'
3. Add a new one and search for mikroktik router
4. Fill out all details and submit
5. See error 'Unknown error occurred'

**Expected behavior**
The integration for mikrotik is added.

**Log**
```
Error handling request
Traceback (most recent call last):
  File "/config/custom_components/mikrotik_router/mikrotikapi.py", line 57, in connect
    self._connection = librouteros.connect(self._host, self._username, self._password, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/librouteros/__init__.py", line 48, in connect
TypeError: 'str' object is not callable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 418, in start
    resp = await task
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_app.py", line 458, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/real_ip.py", line 40, in real_ip_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 73, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 136, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 123, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 163, in post
    return await super().post(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 48, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 90, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 89, in async_configure
    result = await self._async_handle_step(flow, cur_step["step_id"], user_input)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 132, in _async_handle_step
    result: Dict = await getattr(flow, method)(user_input)
  File "/config/custom_components/mikrotik_router/config_flow.py", line 72, in async_step_user
    if not api.connect():
  File "/config/custom_components/mikrotik_router/mikrotikapi.py", line 61, in connect
    librouteros.exceptions.ConnectionClosed,
AttributeError: module 'librouteros.exceptions' has no attribute 'ConnectionClosed'
```

**Software (please complete the following information):**
 - Hass.io / Home Assistant version: Hassio v193/ HA v0.103.0b0
 - Mikrotik Router version: ?
 - Mikrotik Hardware: hAP ac²
 - Mikrotik Software version: v6.44.5

**Additional context**

**Comment by tomaae** [comment]
Thats from within an exception. Required library librouteros v3.0.0 does have ConnectionClosed exception.
Did you installed different librouteros version over it?
Which Mikrotik Router integration version did you installed?

**Comment by tomaae** [comment]
I have installed new HA instance with hacs and installation/configuration works perfectly fine.
Looks like you have a requirements conflict. Possibly a different integration which locks librouteros to lower version.

**Comment by tomaae** [comment]
Can you have a look for what is causing a conflict?
If you are not able to, let me know what kind of other mikrotik related integrations do you have installed.
Not sure I can do anything about this one, but I will try to look for a workaround.

**Comment by tjorim** [comment]
Built-in mikrotik hub integration has requirement "librouteros==2.3.0".
https://github.com/home-assistant/home-assistant/blob/dev/homeassistant/components/mikrotik/manifest.json

**Comment by tomaae** [comment]
Give v1.1.2 a try, I have integrated the library to avoid any conflicts with other integrations

**Comment by myownkaos** [comment]
> Give v1.1.2 a try, I have integrated the library to avoid any conflicts with other integrations

i was having the same issue as @tjorim but at the moment at integration menu when i click the mikrotik it doesnt even come up.

**Comment by tomaae** [comment]
> 
> 
> > Give v1.1.2 a try, I have integrated the library to avoid any conflicts with other integrations
> 
> i was having the same issue as @tjorim but at the moment at integration menu when i click the mikrotik it doesnt even come up.
> 
> > Error occurred loading config flow for integration mikrotik_router: cannot import name 'ConnectionClosed' from 'librouteros.exceptions' (/usr/local/lib/python3.7/site-packages/librouteros/exceptions.py)

is that with v1.1.2?

**Comment by tjorim** [comment]
Yes with 1.1.2, that's the only line in the log.

**Comment by tomaae** [comment]
Do you use any other integration then build-in HA mikrotik presence detection? I have tried to use that one and while it crashes since it dont follow mikrotik standards, I'm not getting any conflicts with 2.3.0 installed under HA.
I need to find a way to reproduce it, since there is no traceback.

**Comment by tomaae** [comment]
Give v1.1.3 a try, I'm now able to run both integration at the same time.

**Comment by tjorim** [comment]
Working almost perfect now, one new issue: #3.
