### ISSUE TITLE
[Bug] AttributeError: 'NoneType' object has no attribute 'async_create_task'

### ISSUE THREAD

**Issue by tjorim** [tomaae/homeassistant-mikrotik_router#3]
**Describe the bug**
Getting an error, not sure what's missing.

**To Reproduce**
1. Set up the integration.
2. Happens after that and on each reboot.

**Expected behavior**
No errors.

**Screenshots**
Error while setting up platform mikrotik_router
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 150, in _async_setup_platform
    await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
  File "/config/custom_components/mikrotik_router/switch.py", line 89, in async_setup_entry
    update_controller()
  File "/config/custom_components/mikrotik_router/switch.py", line 83, in update_controller
    update_items(inst, mikrotik_controller, async_add_entities, switches)
  File "/config/custom_components/mikrotik_router/switch.py", line 107, in update_items
    switches[item_id].async_schedule_update_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 432, in async_schedule_update_ha_state
    self.hass.async_create_task(self.async_update_ha_state(force_refresh))
AttributeError: 'NoneType' object has no attribute 'async_create_task'

**Software (please complete the following information):**
 - Hass.io / Home Assistant version: Hassio v193/ HA v0.103.0b0
 - Mikrotik Hardware: hAP ac²
 - Mikrotik Software version: v6.44.5

**Additional context**

**Comment by tomaae** [comment]
What do you mean by `Happens after that and on each reboot.` ?
Like HA restart or hassio reboot? Or is that on mikrotik reboot?

**Comment by tjorim** [comment]
HA restart, probably because it sets up the integration tasks.

**Comment by tjorim** [comment]
Probably a related message in the logs:
```
Exception in update_controller when dispatching 'mikrotik_router-update-Mikrotik': ()
Traceback (most recent call last):
  File "/config/custom_components/mikrotik_router/switch.py", line 83, in update_controller
    update_items(inst, mikrotik_controller, async_add_entities, switches)
  File "/config/custom_components/mikrotik_router/switch.py", line 107, in update_items
    switches[item_id].async_schedule_update_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 432, in async_schedule_update_ha_state
    self.hass.async_create_task(self.async_update_ha_state(force_refresh))
AttributeError: 'NoneType' object has no attribute 'async_create_task'
```

**Comment by tomaae** [comment]
do you have any scripts without a name?

**Comment by myownkaos** [comment]
should i remove the mikrotik integration?

**Comment by tomaae** [comment]
> 
> 
> should i remove the mikrotik integration?

Removing different integration is not a solution, so no. But I dont think this is a conflict. Can be a missing script name which I just workarounded in master.
Do you have the same issue?

**Comment by myownkaos** [comment]
i added the integration no problem but no devices.

**Comment by tomaae** [comment]
Is it the same traceback error? Do you have any scripts on your mikrotik device without a name?

**Comment by myownkaos** [comment]
no scripts at my router.

> Error doing job: Task exception was never retrieved
> Traceback (most recent call last):
>   File "/config/custom_components/mikrotik_router/mikrotik_controller.py", line 86, in force_update
>     await self.async_update()
>   File "/config/custom_components/mikrotik_router/mikrotik_controller.py", line 156, in async_update
>     await self.async_fwupdate_check()
>   File "/config/custom_components/mikrotik_router/mikrotik_controller.py", line 144, in async_fwupdate_check
>     self.get_firmare_update()
>   File "/config/custom_components/mikrotik_router/mikrotik_controller.py", line 436, in get_firmare_update
>     self.data['fw-update']['available'] = True if entry['status'] == "New version is available" else False
> KeyError: 'status'

**Comment by tomaae** [comment]
thats a different issue. can you give me output from your router?
`/system package update check-for-updates`

**Comment by myownkaos** [comment]
> thats a different issue. can you give me output from your router?
> `/system package update check-for-updates`
> 
> If you can, open a new issue for it, so we wont mix things up

started to work. all of a sudden.

**Comment by tjorim** [comment]
> do you have any scripts without a name?

No, both have a name: 
![image](https://user-images.githubusercontent.com/1294876/70395067-5f06fa80-19fb-11ea-9dc7-1d1eb6dc8140.png)

Which group policies should the user have?
For the HA device tracker I use this: 
![image](https://user-images.githubusercontent.com/1294876/70395084-83fb6d80-19fb-11ea-9c5b-47d633c3b3b4.png)

**Comment by tomaae** [comment]
It also needs write access for switches.
I still did not figured out scripts rights for scripts

**Comment by tomaae** [comment]
> 
> 
> > thats a different issue. can you give me output from your router?
> > `/system package update check-for-updates`
> > If you can, open a new issue for it, so we wont mix things up
> 
> started to work. all of a sudden.

found the reason. status is missing on first query after firmware upgrade. probably a routeros bug, but easy to fix from my side. will be in next release.

**Comment by tomaae** [comment]
I cannot find any other possible cause.
Can you provide output of these 4 commands? Feel free to obscure any data. Just dont delete the entries, but replace them with something obvious(like XX).

`/interface print terse`
`/ip arp print terse`
`/interface bridge host print terse`
`/ip firewall nat print terse`

**Comment by tjorim** [comment]
> It also needs write access for switches.
> I still did not figured out scripts rights for scripts

Gave it write access, no difference.

> I cannot find any other possible cause.
> Can you provide output of these 4 commands? Feel free to obscure any data. Just dont delete the entries, but replace them with something obvious(like XX).
> 
> `/interface print terse`
> `/ip arp print terse`
> `/interface bridge host print terse`
> `/ip firewall nat print terse`

Is this aimed at me?

**Comment by tomaae** [comment]
yes, thanks. I will go through it when I get home.
your problem is not related to access rights. I suspect there is something missing or reported in different way in api response, but I have to take a look at that in detail.
I just remember that I should have cAP somewhere. That is a wifi, so I will test it with that one too. Could be something related to wifi interface.

**Comment by tomaae** [comment]
I cant find anything obvious.
I have started refactoring and adding debugs to the controller class. It may take me a day or two, but afterwards we should be able to find the issue fast, if it still persists after changes.

**Comment by tomaae** [comment]
I have not finished with everything but you can give it a try, if you feel like it.
just select manually master version under HACS

to debug, set up your logger like this:
```
logger:
  default: info
  logs:
    custom_components.mikrotik_router: debug

but test first, that debug may be quite a json wall

**Comment by tjorim** [comment]
I updated to master and adjusted the logger settings, however, there is no extra info in the logs.

**Comment by tomaae** [comment]
can you give me current error?

**Comment by tjorim** [comment]
I deleted the integration, rebooted and set it up again. The following error shows up:
```
Error while setting up platform mikrotik_router
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 150, in _async_setup_platform
    await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
  File "/config/custom_components/mikrotik_router/switch.py", line 83, in async_setup_entry
    update_controller()
  File "/config/custom_components/mikrotik_router/switch.py", line 77, in update_controller
    update_items(inst, mikrotik_controller, async_add_entities, switches)
  File "/config/custom_components/mikrotik_router/switch.py", line 103, in update_items
    switches[item_id].async_schedule_update_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 432, in async_schedule_update_ha_state
    self.hass.async_create_task(self.async_update_ha_state(force_refresh))
AttributeError: 'NoneType' object has no attribute 'async_create_task'
```

**Comment by tomaae** [comment]
I'm really confused by this. Since you for to line 103, it means you already have switch components added in HA and they are updating status.
Logging failing just does not seem possible. Maybe you are overwriting logging somewhere?

Btw, I have tested with wifi device. Problem is certainly not in that:
![image](https://user-images.githubusercontent.com/23486452/71196272-043d9080-2290-11ea-8b0e-0e0b3e4a2d9e.png)
![image](https://user-images.githubusercontent.com/23486452/71196281-09024480-2290-11ea-887d-c6b43f7b3a12.png)

If you cannot get working, you could try to figure out which switch type is causing the issue.
You can find all types in switch.py on line 96:
![image](https://user-images.githubusercontent.com/23486452/71196382-4070f100-2290-11ea-907d-8ec0b4ffe9b6.png)
Just try with one value at the time to figure out what is causing the issue. I suspect it could be NAT, since thats the most complicated and still not refactored.

**Comment by volshebniks** [comment]
I got  the following error:
Fri Dec 20 2019 13:23:45 GMT+0300 (Москва, стандартное время)
Error setting up entry Mikrotik_R for mikrotik_router
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 192, in async_setup
    hass, self
  File "/config/custom_components/mikrotik_router/__init__.py", line 48, in async_setup_entry
    await mikrotik_controller.async_update()
  File "/config/custom_components/mikrotik_router/mikrotik_controller.py", line 160, in async_update
    self.get_nat()
  File "/config/custom_components/mikrotik_router/mikrotik_controller.py", line 391, in get_nat
    self.data['nat'][uid]['name'] = "{}:{}".format(entry['protocol'], entry['dst-port'])
KeyError: 'dst-port'

**Comment by tomaae** [comment]
Could be related, but that’s a different error. Can you open new issue and mention your HA, mikrotik_router and router is versions?
I take a look at what’s wrong

**Comment by tjorim** [comment]
Seems like NAT is the problem, this works:
![image](https://user-images.githubusercontent.com/1294876/71307013-9b1d6080-23e8-11ea-9152-b1ce4813ad42.png)

**Comment by tomaae** [comment]
Hmm, you dont have any NAT rule which would be out of ordinary.
Since debugs dont work for you, add a following above line 103 (`switches[item_id].async_schedule_update_ha_state()`) where it fails:
`print("Updating {} switch: {}".format(sid, item_id))`
So we know which rule it fails on.

**Comment by tjorim** [comment]
```
2019-12-21 15:23:13 INFO (MainThread) [homeassistant.components.switch] Setting up switch.mikrotik_router
2019-12-21 15:23:13 INFO (MainThread) [custom_components.mikrotik_router.switch] Updating nat switch: Mikrotik-nat-tcp:8090
2019-12-21 15:23:13 ERROR (MainThread) [homeassistant.components.switch] Error while setting up platform mikrotik_router
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 150, in _async_setup_platform
    await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
  File "/config/custom_components/mikrotik_router/switch.py", line 83, in async_setup_entry
    update_controller()
  File "/config/custom_components/mikrotik_router/switch.py", line 77, in update_controller
    update_items(inst, mikrotik_controller, async_add_entities, switches)
  File "/config/custom_components/mikrotik_router/switch.py", line 106, in update_items
    switches[item_id].async_schedule_update_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 432, in async_schedule_update_ha_state
    self.hass.async_create_task(self.async_update_ha_state(force_refresh))
AttributeError: 'NoneType' object has no attribute 'async_create_task'
```
and
```
2019-12-21 15:23:42 INFO (MainThread) [custom_components.mikrotik_router.switch] Updating interface switch: Mikrotik-interface-ether1
2019-12-21 15:23:42 ERROR (MainThread) [homeassistant.util.logging] Exception in update_controller when dispatching 'mikrotik_router-update-Mikrotik': ()
Traceback (most recent call last):
  File "/config/custom_components/mikrotik_router/switch.py", line 77, in update_controller
    update_items(inst, mikrotik_controller, async_add_entities, switches)
  File "/config/custom_components/mikrotik_router/switch.py", line 106, in update_items
    switches[item_id].async_schedule_update_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 432, in async_schedule_update_ha_state
    self.hass.async_create_task(self.async_update_ha_state(force_refresh))
AttributeError: 'NoneType' object has no attribute 'async_create_task'
```
Didn't realise the log is only in the file and not HA Developer Tools.

**Comment by tjorim** [comment]
Fixed with @tomaae via Discord. It was a user error.
I had two NAT rules with the same destination port.
