### ISSUE TITLE
Add support for old Mikrotik OS versions

### ISSUE THREAD

**Issue by enzon0** [tomaae/homeassistant-mikrotik_router#4]
hassio 0.102.3
RB2011UAS-2HnD version 6.22

hassio log:
Traceback (most recent call last):
  File "/config/custom_components/mikrotik_router/mikrotik_controller.py", line 86, in force_update
    await self.async_update()
  File "/config/custom_components/mikrotik_router/mikrotik_controller.py", line 156, in async_update
    await self.async_fwupdate_check()
  File "/config/custom_components/mikrotik_router/mikrotik_controller.py", line 144, in async_fwupdate_check
    self.get_firmare_update()
  File "/config/custom_components/mikrotik_router/mikrotik_controller.py", line 452, in get_firmare_update
    data = self.api.path("/system/package/update")
  File "/config/custom_components/mikrotik_router/mikrotikapi.py", line 125, in path
    tuple(response)
  File "/config/custom_components/mikrotik_router/librouteros_custom/api.py", line 103, in __iter__
    yield from self('print')
  File "/config/custom_components/mikrotik_router/librouteros_custom/api.py", line 108, in __call__
    **kwargs,
  File "/config/custom_components/mikrotik_router/librouteros_custom/api.py", line 27, in __call__
    self.protocol.writeSentence(cmd, *words)
  File "/config/custom_components/mikrotik_router/librouteros_custom/protocol.py", line 181, in writeSentence
    self.transport.write(encoded)
  File "/config/custom_components/mikrotik_router/librouteros_custom/connections.py", line 16, in write
    self.sock.sendall(data)

**Comment by tomaae** [comment]
which version are you using?

**Comment by enzon0** [comment]
now: v1.1.4

for while: v 1.1.3 that same effect.

**Comment by tomaae** [comment]
6.22 is quite old version. I know there were some change in login method some time ago, but not sure which version was a cutting point.
I will install that version on one of my old routers, if its still available for download and see what I can do.
But it may take a bit since I'm refactoring controller class right now.

**Comment by enzon0** [comment]
on 6.22 i have the best transfer. in every version after processor ends on 50Mbps less.

**Comment by tomaae** [comment]
thats interesting. I was using rb2011 for years, just until recently. I still have it, so I can install 6.22 there and work on compatibility with old version.
I just need some time to finish what I'm working on right now, it wont take long.

**Comment by enzon0** [comment]
its working after router update to 6.44.6, but transfer is180Mbps :( . On 6.22 is full speed 300Mbps.

**Comment by tomaae** [comment]
I certainly had 300Mbps on my rb2011 with FP O.o
But no worries, I will make it work on older versions.

**Comment by enzon0** [comment]
i have a fiber connection and 3 vlans (internet, tv, vod)
tv and vod are bridged with one ether with priority change- that kills cpu.

today I have been testing hap2  (arm 4 cores) CPU - 9% with the same config.

**Comment by tomaae** [comment]
I have rb4011. It’s a beast of a machine, amazing direct upgrade to rb2011.

**Comment by tomaae** [comment]
sorry it is taking longer, its just bit hectic now before xmas. I have not forgotten about this.

**Comment by enzon0** [comment]
has stopped working with version 1.1XX.X

**Comment by tomaae** [comment]
I guess that was same time they upgraded to new librouteros

**Comment by enzon0** [comment]
it's possible. I am waiting for the end of crazy things with covid and I will buy RB4011 and the old version problem ends.

**Comment by tomaae** [comment]
yeah, I'm afraid that will be the only solution if you want to integrate it. I have tried all possible ways, but could not get past authentication.
