### ISSUE TITLE
[Bug] Fix hass startup when device is offline

### ISSUE THREAD

**Issue by tomaae** [tomaae/homeassistant-mikrotik_router#7]
Entity initialization fails when device is offline during hass boot

**Comment by tomaae** [comment]
Mikrotik 192.168.12.1 error while path timed out
Error doing job: Task exception was never retrievedTraceback (most recent call last): File "/config/custom_components/mikrotik_router/mikrotik_controller.py", line 57, in force_update await self.async_update() File "/config/custom_components/mikrotik_router/mikrotik_controller.py", line 135, in async_update await self.hass.async_add_executor_job(self.get_interface_client) File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run result = self.fn(*self.args, **self.kwargs) File "/config/custom_components/mikrotik_router/mikrotik_controller.py", line 239, in get_interface_client mac2ip, bridge_used = self.update_arp(mac2ip, bridge_used) File "/config/custom_components/mikrotik_router/mikrotik_controller.py", line 263, in update_arp if entry['invalid']: KeyError: 'invalid'

**Comment by tomaae** [comment]
>2020-01-13 14:31:01 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/mikrotik_router/mikrotik_controller.py", line 64, in force_fwupdate_check
    await self.async_fwupdate_check()
  File "/config/custom_components/mikrotik_router/mikrotik_controller.py", line 117, in async_fwupdate_check
    await self.hass.async_add_executor_job(self.get_firmware_update)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/mikrotik_router/mikrotik_controller.py", line 430, in get_firmware_update
    {'name': 'latest-version', 'default': 'unknown'}
  File "/config/custom_components/mikrotik_router/helper.py", line 48, in parse_api
    for entry in source:
  File "/config/custom_components/mikrotik_router/librouteros_custom/api.py", line 103, in __iter__
    yield from self('print')
  File "/config/custom_components/mikrotik_router/librouteros_custom/api.py", line 108, in __call__
    **kwargs,
  File "/config/custom_components/mikrotik_router/librouteros_custom/api.py", line 28, in __call__
    yield from self.readResponse()
  File "/config/custom_components/mikrotik_router/librouteros_custom/api.py", line 60, in readResponse
    reply_word, words = self.readSentence()
  File "/config/custom_components/mikrotik_router/librouteros_custom/api.py", line 46, in readSentence
    reply_word, words = self.protocol.readSentence()
  File "/config/custom_components/mikrotik_router/librouteros_custom/protocol.py", line 189, in readSentence
    sentence = tuple(word for word in iter(self.readWord, ''))
  File "/config/custom_components/mikrotik_router/librouteros_custom/protocol.py", line 189, in <genexpr>
    sentence = tuple(word for word in iter(self.readWord, ''))
  File "/config/custom_components/mikrotik_router/librouteros_custom/protocol.py", line 205, in readWord
    word = self.transport.read(length)
  File "/config/custom_components/mikrotik_router/librouteros_custom/connections.py", line 25, in read
    data += self.sock.recv((length - len(data)))
socket.timeout: timed out
