### ISSUE TITLE
[Bug] Firmware Update 

### ISSUE THREAD

**Issue by ckiliboz** [tomaae/homeassistant-mikrotik_router#96]
## Describe the issue

How does the firmware update sensor behaves? I'm on stable branch and all devices were on 6.48, firmware update still shows 'Off' even though 6.48.1 is released.

## Expected behavior

Firmware update value to be 'On'

## Software versions

 - Home Assistant version: 
 - Mikrotik Router integration version: 
 - Mikrotik Hardware: 
 - RouterOS version:

**Comment by ckiliboz** [comment]
Could there be a reason why the update was not shown? I was expecting as soon as a new version is released, sensor value to be On.

**Comment by firemdkfighter** [comment]
In logs:
```
2021-02-25 19:38:48 ERROR (MainThread) [homeassistant.util.logging] Exception in update_controller when dispatching 'mikrotik_router-update-Mikrotik': ()
Traceback (most recent call last):
  File "/volume1/@appstore/homeassistant/var/config/custom_components/mikrotik_router/sensor.py", line 211, in update_controller
    inst, config_entry, mikrotik_controller, async_add_entities, sensors
  File "/volume1/@appstore/homeassistant/var/config/custom_components/mikrotik_router/sensor.py", line 304, in update_items
    sensors[item_id].async_schedule_update_ha_state()
  File "/volume1/@appstore/homeassistant/env/lib/python3.7/site-packages/homeassistant/helpers/entity.py", line 441, in async_schedule_update_ha_state
    self.async_write_ha_state()
  File "/volume1/@appstore/homeassistant/env/lib/python3.7/site-packages/homeassistant/helpers/entity.py", line 293, in async_write_ha_state
    f"No entity id specified for entity {self.name}"
    ```

**Comment by tomaae** [comment]
you will need to debug this one, not sure how this can even happen

**Comment by firemdkfighter** [comment]
Sensor working...

**Comment by tomaae** [comment]
Did it just "fixed itself"?

**Comment by firemdkfighter** [comment]
I'm rebooting HA. And it just working...
